# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

container: grahamschock/suneed_env:latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
        git clone https://github.com/grahamschock/power_mgmt_infra.git
  displayName: 'Clone system'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      cd src/nng
      cmake -G Ninja ..
      ninja
      ninja test
      ninja install
  displayName: 'Build nng'